backend:
  name: github
  repo: username/your-repo
  branch: main
  client_id: Ov23ligiluF6N1mYGE4Y

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/data/blogs"
    create: true
    path: "{{slug}}"
    fields:
      - { label: "Tiêu đề", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Ngày đăng", name: "date", widget: "datetime" }
      - { label: "Nội dung", name: "body", widget: "markdown" }
